// PrismStructure/src/pages/RegisterPage.js

export class RegisterPage {
    /**
     * @param {import('@playwright/test').Page} page
     */
    constructor(page) {
      this.page = page;

      // Exact locators matching Practice Software Testing (Toolshop v5)
      this.firstNameInput = page.locator('#first_name, [data-test="first-name"]');
      this.lastNameInput = page.locator('#last_name, [data-test="last-name"]');
      this.dobInput = page.locator('#dob, [data-test="dob"]');
      this.countrySelect = page.locator('#country, [data-test="country"]');
      this.postcodeInput = page.locator('#postal_code, #postcode, [data-test="postal-code"]');
      this.houseNumberInput = page.locator('#street_number, #house_number, [data-test="street-number"]');
      this.addressInput = page.locator('#street, #address, [data-test="address"]');
      this.cityInput = page.locator('#city, [data-test="city"]');
      this.stateInput = page.locator('#state, [data-test="state"]');
      this.phoneInput = page.locator('#phone, [data-test="phone"]');
      this.emailInput = page.locator('#email, [data-test="email"]');
      this.passwordInput = page.locator('#password, [data-test="password"]');
      this.registerBtn = page.locator('button[data-test="register-submit"], input[type="submit"], button:has-text("Register")');
    }

    async navigate() {
      await this.page.goto('/auth/register');
      await this.page.waitForLoadState('domcontentloaded');
    }

    /**
     * Fills and submits registration form using TestDataFactory payload
     * @param {Object} userData - Object generated by TestDataFactory.generateUserData()
     */
    async registerUser(userData) {
      await this.firstNameInput.fill(userData.first_name);
      await this.lastNameInput.fill(userData.last_name);
      
      // DOB requires YYYY-MM-DD
      await this.dobInput.fill(userData.dob || '1995-01-01');

      // Country selection
      if (userData.country) {
        await this.countrySelect.selectOption(userData.country);
      } else {
        await this.countrySelect.selectOption('US');
      }
      
      // Fill Postal Code & House Number (required)
      await this.postcodeInput.fill(userData.postcode || userData.postal_code || '12345');
      
      // Ensure House Number is filled if present
      if (await this.houseNumberInput.isVisible().catch(() => false)) {
        await this.houseNumberInput.fill(userData.house_number || userData.street_number || '42');
      }

      // Address details
      await this.addressInput.fill(userData.address || userData.street || 'Main Street 1');
      await this.cityInput.fill(userData.city || 'Anytown');
      await this.stateInput.fill(userData.state || 'State');

      // Contact & Login details
      // Clean phone to only digits if required by validation rules
      const cleanPhone = (userData.phone || '1234567890').toString().replace(/\D/g, '');
      await this.phoneInput.fill(cleanPhone || '1234567890');

      await this.emailInput.fill(userData.email);
      await this.passwordInput.fill(userData.password);

      // Submit
      await this.registerBtn.click();
      await this.page.waitForURL(/\/auth\/login/, { timeout: 30000 });
    }
}